# Generated by Django 5.2.7 on 2025-10-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_tweet_retweet_like_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweetImage',
        ),
    ]
